# This workflow will install Python dependencies, run Covid19_update.py file with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python covid update

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Scripts/Covid/requirements.txt
    - name: updated figs
      run: |
        python Scripts/Covid/Covid19_update.py ${{secrets.chart_plotly_name}} ${{secrets.chart_plotly_clave}}
        python Scripts/Covid/Covid19_BarChartRace_update.py
