# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python covid update

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.6..9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Scripts/Covid/
        pip install -r requirements.txt
    - name: updated figs
      run: |
        Covid19_update.py ${{secrets.chart_plotly_name}} ${{secrets.chart_plotly_clave}}
